version: "3.9"

services:
    redis:
      image: redis:7
      restart: always
      container_name: redis
      ports:
        - "6379:6379"
    app:
      build: .
      container_name: asyncio-parser
      depends_on:
        - redis
